apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: app-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-pv
spec:
  claimRef:
    name: app-pvc
    namespace: default 
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /test
