apiVersion: v1
kind: PersistentVolume
metadata:
  name: django-web-blog-media-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /test
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-web-blog-media-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: django-web-blog-media-pv